using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RSApiClient.Hiscores.Models
{
    public enum OSRSHiscoresCsvMapping : int
    {
		Overall = 0,
		Attack = 1,
		Defence = 2,
		Strength = 3,
		Hitpoints = 4,
		Ranged = 5,
		Prayer = 6,
		Magic = 7,
		Cooking = 8,
		Woodcutting = 9,
		Fletching = 10,
		Fishing = 11,
		Firemaking = 12,
		Crafting = 13,
		Smithing = 14,
		Mining = 15,
		Herblore = 16,
		Agility = 17,
		Thieving = 18,
		Slayer = 19,
		Farming = 20,
		Runecrafting = 21,
		Hunter = 22,
		Construction = 23,
		LeaguePoints = 24,
		BountyHunter_Hunter = 25,
		BountyHunter_Rogue = 26,
		ClueScrolls_All = 27,
		ClueScrolls_Beginner = 28,
		ClueScrolls_Easy = 29,
		ClueScrolls_Medium = 30,
		ClueScrolls_Hard = 31,
		ClueScrolls_Elite = 32,
		ClueScrolls_Master = 33,
		LastManStanding = 34,
		SoulWarsZeal = 35,
		AbyssalSire = 36,
		AlchemicalHydra = 37,
		BarrowsChests = 38,
		Bryophyta = 39,
		Callisto = 40,
		Cerberus = 41,
		ChambersOfXeric = 42,
		ChambersOfXeric_ChallengeMode = 43,
		ChaosElemental = 44,
		ChaosFanatic = 45,
		CommanderZilyana = 46,
		CorporealBeast = 47,
		CrazyArchaeologist = 48,
		DagannothPrime = 49,
		DagannothRex = 50,
		DagannothSupreme = 51,
		DerangedArchaeologist = 52,
		GeneralGraardor = 53,
		GiantMole = 54,
		GrotesqueGuardians = 55,
		Hespori = 56,
		KalphiteQueen = 57,
		KingBlackDragon = 58,
		Kraken = 59,
		Kreearra = 60,
		KrilTsutsaroth = 61,
		Mimic = 62,
		Nightmare = 63,
		PhosanisNightmare = 64,
		Obor = 65,
		Sarachnis = 66,
		Scorpia = 67,
		Skotizo = 68,
		Tempoross = 69,
		TheGauntlet = 70,
		TheCorruptedGauntlet = 71,
		TheatreOfBlood = 72,
		TheatreOfBlood_HardMode = 73,
		ThermonuclearSmokeDevil = 74,
		TzkalZuk = 75,
		TztokJad = 76,
		Venenatis = 77,
		Vetion = 78,
		Vorkath = 79,
		Wintertodt = 80,
		Zalcano = 81,
		Zulrah = 82
	}
}
