using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RSApiClient.Hiscores.Models
{
    public enum RS3HiscoresCsvMapping : int
    {
		Overall = 0,
		Attack = 1,
		Defence = 2,
		Strength = 3,
		Constitution = 4,
		Ranged = 5,
		Prayer = 6,
		Magic = 7,
		Cooking = 8,
		Woodcutting = 9,
		Fletching = 10,
		Fishing = 11,
		Firemaking = 12,
		Crafting = 13,
		Smithing = 14,
		Mining = 15,
		Herblore = 16,
		Agility = 17,
		Thieving = 18,
		Slayer = 19,
		Farming = 20,
		Runecrafting = 21,
		Hunter = 22,
		Construction = 23,
		Summoning = 24,
        Dungeoneering = 25,
        Divination = 26,
        Invention = 27,
        Archaeology = 28,
		BountyHunter = 29,
		BountyHunter_Rogues = 30,
		DominionTower = 31,
		TheCrucible = 32,
		CastleWarsGames = 33,
		BarbarianAssault_Attacker = 34,
		BarbarianAssault_Defender = 35,
		BarbarianAssault_Collector = 36,
		BarbarianAssault_Healer = 37,
		DuelTournament = 38,
		MobilisingArmies = 39,
		Conquest = 40,
		FistOfGuthix = 41,
		GielinorGames_Athletics = 42,
		GielinorGames_ResourceRace = 43,
		WorldEvent2_ArmadylLifetimeContribution = 44,
		WorldEvent2_BandosLifetimeContribution = 45,
		WorldEvent2_ArmadylPvpKills = 46,
		WorldEvent2_BandosPvpKills = 47,
		HeistGuardLevel = 48,
		HeistRobberLevel = 49,
		CabbageFacepunchBonanza_5GameAverage = 50,
		AprilFools2015_CowTipping = 51,
		AprilFools2015_RatsKilledAfterMiniquest = 52,
		Runescore = 53,
		ClueScrolls_Easy = 54,
		ClueScrolls_Medium = 55,
		ClueScrolls_Hard = 56,
		ClueScrolls_Elite = 57,
		ClueScrolls_Master = 58,
	}
}
